
import java.awt.Color;
import static java.awt.Color.RED;
import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nS
 */
public class HlavniOkno extends javax.swing.JFrame {

    double PrvniCislo;
    double DruheCislo;
    double vysledek;
    String operace = "";
    
    public HlavniOkno() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPromenne = new javax.swing.JTextField();
        jButton01 = new javax.swing.JButton();
        jButton03 = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButton02 = new javax.swing.JButton();
        jButton04 = new javax.swing.JButton();
        jButton06 = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButton05 = new javax.swing.JButton();
        jButton07 = new javax.swing.JButton();
        jButton09 = new javax.swing.JButton();
        jButtonNasob = new javax.swing.JButton();
        jButton08 = new javax.swing.JButton();
        jButtonPluMin = new javax.swing.JButton();
        jButtonDesCarka = new javax.swing.JButton();
        jButtonDeleni = new javax.swing.JButton();
        jButton00 = new javax.swing.JButton();
        jButtonVynuluj = new javax.swing.JButton();
        jButtonVysledek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulačka ULTRA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("jFRAME"); // NOI18N
        setResizable(false);

        jTextFieldPromenne.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextFieldPromenne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPromenneActionPerformed(evt);
            }
        });

        jButton01.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton01.setText("1");
        jButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton01ActionPerformed(evt);
            }
        });

        jButton03.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton03.setText("3");
        jButton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton03ActionPerformed(evt);
            }
        });

        jButtonPlus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPlus.setText("+");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });

        jButton02.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton02.setText("2");
        jButton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton02ActionPerformed(evt);
            }
        });

        jButton04.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton04.setText("4");
        jButton04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton04ActionPerformed(evt);
            }
        });

        jButton06.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton06.setText("6");
        jButton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton06ActionPerformed(evt);
            }
        });

        jButtonMinus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonMinus.setText("-");
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });

        jButton05.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton05.setText("5");
        jButton05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton05ActionPerformed(evt);
            }
        });

        jButton07.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton07.setText("7");
        jButton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton07ActionPerformed(evt);
            }
        });

        jButton09.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton09.setText("9");
        jButton09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton09ActionPerformed(evt);
            }
        });

        jButtonNasob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNasob.setText("*");
        jButtonNasob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNasobActionPerformed(evt);
            }
        });

        jButton08.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton08.setText("8");
        jButton08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton08ActionPerformed(evt);
            }
        });

        jButtonPluMin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPluMin.setText("+/-");
        jButtonPluMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPluMinActionPerformed(evt);
            }
        });

        jButtonDesCarka.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDesCarka.setText(".");
        jButtonDesCarka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesCarkaActionPerformed(evt);
            }
        });

        jButtonDeleni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDeleni.setText("/");
        jButtonDeleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleniActionPerformed(evt);
            }
        });

        jButton00.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton00.setText("0");
        jButton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton00ActionPerformed(evt);
            }
        });

        jButtonVynuluj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVynuluj.setText("C");
        jButtonVynuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVynulujActionPerformed(evt);
            }
        });

        jButtonVysledek.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVysledek.setText("=");
        jButtonVysledek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVysledekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldPromenne)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton01, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)
                            .addComponent(jButton03, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton04, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton05, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButton06, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton07, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton08, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButton09, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNasob, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonVynuluj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonPluMin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDesCarka, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDeleni, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonVysledek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldPromenne, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton01, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton03, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton04, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton06, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton05, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton07, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton09, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNasob, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton08, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPluMin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDesCarka, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleni, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVynuluj, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVysledek, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("Tohle je ta nejlepšejší kalkulačka, jakou jste mohli koupit. (Doufm, že jste ji koupili)");

        setSize(new java.awt.Dimension(317, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton07ActionPerformed
        
        String vlozCislo = jTextFieldPromenne.getText() + jButton07.getText();
        jTextFieldPromenne.setText(vlozCislo);
    }//GEN-LAST:event_jButton07ActionPerformed

    private void jButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton01ActionPerformed
        
        String vlozCislo = jTextFieldPromenne.getText() + jButton01.getText();
        jTextFieldPromenne.setText(vlozCislo);
    }//GEN-LAST:event_jButton01ActionPerformed

    private void jButton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton02ActionPerformed
        
        String vlozCislo = jTextFieldPromenne.getText() + jButton02.getText();
        jTextFieldPromenne.setText(vlozCislo);
    }//GEN-LAST:event_jButton02ActionPerformed

    private void jButton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton03ActionPerformed
        String vlozCislo = jTextFieldPromenne.getText() + jButton03.getText();
        jTextFieldPromenne.setText(vlozCislo);
    }//GEN-LAST:event_jButton03ActionPerformed

    private void jButton04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton04ActionPerformed
        
        String vlozCislo = jTextFieldPromenne.getText() + jButton04.getText();
        jTextFieldPromenne.setText(vlozCislo);
    }//GEN-LAST:event_jButton04ActionPerformed

    private void jButton05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton05ActionPerformed
        
        String vlozCislo = jTextFieldPromenne.getText() + jButton05.getText();
        jTextFieldPromenne.setText(vlozCislo);
    }//GEN-LAST:event_jButton05ActionPerformed

    private void jButton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton06ActionPerformed
        String vlozCislo = jTextFieldPromenne.getText() + jButton06.getText();
        jTextFieldPromenne.setText(vlozCislo);
    }//GEN-LAST:event_jButton06ActionPerformed

    private void jButton08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton08ActionPerformed
        
        String vlozCislo = jTextFieldPromenne.getText() + jButton08.getText();
        jTextFieldPromenne.setText(vlozCislo);
    }//GEN-LAST:event_jButton08ActionPerformed

    private void jButton09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton09ActionPerformed
        
        String vlozCislo = jTextFieldPromenne.getText() + jButton09.getText();
        jTextFieldPromenne.setText(vlozCislo);
    }//GEN-LAST:event_jButton09ActionPerformed

    private void jButton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton00ActionPerformed

        String vlozCislo = jTextFieldPromenne.getText() + jButton00.getText();
        jTextFieldPromenne.setText(vlozCislo);
    }//GEN-LAST:event_jButton00ActionPerformed

    private void jButtonVynulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVynulujActionPerformed
        jTextFieldPromenne.setText("");
        operace = "";
    }//GEN-LAST:event_jButtonVynulujActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        
        try 
        {
          double n = Double.parseDouble(jTextFieldPromenne.getText());
          PrvniCislo = Double.parseDouble(jTextFieldPromenne.getText());
          jTextFieldPromenne.setText("");
          operace = "+";
        } 
        catch (Exception e)
        {
           JOptionPane.showMessageDialog(this, "To není číslo!","Chyba", JOptionPane.ERROR_MESSAGE);
           jTextFieldPromenne.setText("");
        }         
          
        
        
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        
        try 
        {
          double n = Double.parseDouble(jTextFieldPromenne.getText());
          PrvniCislo = Double.parseDouble(jTextFieldPromenne.getText());
          jTextFieldPromenne.setText("");
          operace = "-";
        } 
        catch (Exception e)
        {
           JOptionPane.showMessageDialog(this, "To není číslo!","Chyba", JOptionPane.ERROR_MESSAGE);
           jTextFieldPromenne.setText("");
        }
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonNasobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNasobActionPerformed
        
       try 
        {
          double n = Double.parseDouble(jTextFieldPromenne.getText());
          PrvniCislo = Double.parseDouble(jTextFieldPromenne.getText());
          jTextFieldPromenne.setText("");
          operace = "*";
        } 
        catch (Exception e)
        {
           JOptionPane.showMessageDialog(this, "To není číslo!","Chyba", JOptionPane.ERROR_MESSAGE);
           jTextFieldPromenne.setText("");
        }
    }//GEN-LAST:event_jButtonNasobActionPerformed

    private void jButtonDeleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleniActionPerformed
        
        try 
        {
          double n = Double.parseDouble(jTextFieldPromenne.getText());
          PrvniCislo = Double.parseDouble(jTextFieldPromenne.getText());
          jTextFieldPromenne.setText("");
          operace = "/";
        } 
        catch (Exception e)
        {
           JOptionPane.showMessageDialog(this, "To není číslo!","Chyba", JOptionPane.ERROR_MESSAGE);
           jTextFieldPromenne.setText("");
        }
    }//GEN-LAST:event_jButtonDeleniActionPerformed

    private void jButtonDesCarkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesCarkaActionPerformed
        String VlozCislo = jTextFieldPromenne.getText() + jButtonDesCarka.getText();
        jTextFieldPromenne.setText(VlozCislo);
    }//GEN-LAST:event_jButtonDesCarkaActionPerformed

    private void jButtonPluMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPluMinActionPerformed
        
        double OPER = Double.parseDouble(String.valueOf(jTextFieldPromenne.getText()));
        OPER = OPER * (-1);
        String temp = String.valueOf(OPER);
        jTextFieldPromenne.setText(temp); //String.format("%.0f",OPER)
        if(OPER<0){
            jTextFieldPromenne.setForeground(Color.RED);
        } else{
            jTextFieldPromenne.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jButtonPluMinActionPerformed

    private void jButtonVysledekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVysledekActionPerformed
        
        String vysl;
        
     if(operace != "")
     {  
        DruheCislo = Double.parseDouble(jTextFieldPromenne.getText());
        if(operace == "+")
        {
            vysledek = PrvniCislo + DruheCislo;
           // vysl = String.format("%.0f",vysledek);
            vysl = String.valueOf(vysledek);
            jTextFieldPromenne.setText(vysl);
        } 
        else if(operace == "-")
        {
            vysledek = PrvniCislo - DruheCislo;
            //vysl = String.format("%.0f",vysledek);
            vysl = String.valueOf(vysledek);
            jTextFieldPromenne.setText(vysl);
        }
        else if(operace == "*")
        {
            vysledek = PrvniCislo * DruheCislo;
            //vysl = String.format("%.0f",vysledek);
            vysl = String.valueOf(vysledek);
            jTextFieldPromenne.setText(vysl);
        }
        else if(operace == "/"){
            if(DruheCislo == 0)
             {
              JOptionPane.showMessageDialog(this, "Nulou dělit nelze!","Chyba", JOptionPane.ERROR_MESSAGE);  
              jTextFieldPromenne.setText("");
             } 
            else
             {
              vysledek = PrvniCislo / DruheCislo;
             //vysl = String.format("%.0f",vysledek);
              vysl = String.valueOf(vysledek);
              jTextFieldPromenne.setText(vysl);
             }
            }
     }
      else 
     {  
         try {
         double vzorec = Float.parseFloat(jTextFieldPromenne.getText());
        // vysl =String.format("%.0f", vzorec);
         vysl = String.valueOf(vysledek);
         jTextFieldPromenne.setText(vysl);
         } catch(Exception e) {
             JOptionPane.showMessageDialog(this,"Toto mi ještě nefunguje :(");
             jTextFieldPromenne.setText("");
         }
     }
    }//GEN-LAST:event_jButtonVysledekActionPerformed

    private void jTextFieldPromenneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPromenneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPromenneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HlavniOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HlavniOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HlavniOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HlavniOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HlavniOkno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton00;
    private javax.swing.JButton jButton01;
    private javax.swing.JButton jButton02;
    private javax.swing.JButton jButton03;
    private javax.swing.JButton jButton04;
    private javax.swing.JButton jButton05;
    private javax.swing.JButton jButton06;
    private javax.swing.JButton jButton07;
    private javax.swing.JButton jButton08;
    private javax.swing.JButton jButton09;
    private javax.swing.JButton jButtonDeleni;
    private javax.swing.JButton jButtonDesCarka;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonNasob;
    private javax.swing.JButton jButtonPluMin;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonVynuluj;
    private javax.swing.JButton jButtonVysledek;
    private javax.swing.JTextField jTextFieldPromenne;
    // End of variables declaration//GEN-END:variables
}
